- name: Setup catalogue service
  hosts: all
  become: true
  vars:
    component: catalogue
  tasks:
    - name: Setup NodeJS
      ansible.builtin.import_tasks: nodejs.yml





#component=catalogue
#schema_type=mongodb
#source comman.sh
#func_nodejs
