    - name: Copy the service file
      ansible.builtin.copy:
        src: "{{ component }}.service"
        dest: /etc/systemd/system/{{component}}.service
    - name: Copy mongo db repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Enable Node js module
      ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
    - name: Install NodeJS application
      ansible.builtin.yum:
        name: nodejs
        state: installed
    - name: User creation and Download application content
      ansible.builtin.import_tasks: pre-req.yml
    - name: Install application dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app
    - name: Restart application service
      ansible.builtin.import_tasks: systemd.yml
    - name: Install mongo shell
      ansible.builtin.yum:
        name: mongodb-org-shell


    - name: Load application schema
      ansible.builtin.shell: mongo --host 172.31.40.180 </app/schema/{{component}}.js
      when: schema is defined
