- name: Setup Payment service
  hosts: all
  become: true
  vars:
    component: payment
  tasks:
    - name: setup python app service
      ansible.builtin.import_tasks: python.yml


#component=payment
#rabbit_mq_pass=$1
#if [ -z ${rabbit_mq_pass} ]; then
#  echo "Imported Password missing"
#  exit
#  fi
#source comman.sh
#func_python

