- name: roboshop User creation
  ansible.builtin.user:
    name: roboshop

- name: Remove application old content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create application directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download application content and extract
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes