- name: Copy the service file
  ansible.builtin.copy:
    src: "{{ component }}".service
    dest: /etc/systemd/system/{{component}}.service
- name: Install python application
  ansible.builtin.yum:
    name:
    - python36
    - gcc
    - python3-devel
    state: installed
- name: Download the application content and extract it
  ansible.builtin.import_tasks: pre-req.yml
- name: Install application dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: Service reload
  ansible.builtin.import_tasks: systemd.yml





#  echo -e "\e[32m#########copy service file #########\e[0m"
#  cp ${component}.service /etc/systemd/system/${component}.service
#  func_exist_status
#  sed -i 's/rabbit_mq_pass/${rabbit_mq_pass}/' /etc/systemd/system/${component}.service
#  echo -e "\e[32m#########reload daemon service #########\e[0m"
#
#  systemctl daemon-reload
#  func_exist_status
#  echo -e "\e[32m#########Install python #########\e[0m"
#  dnf install python36 gcc python3-devel -y
#  func_exist_status
#  echo -e "\e[32m#########copy code files and unzip#########\e[0m"
#  func_prereq
#  echo -e "\e[32m#########Install python dependencies #########\e[0m"
#  pip3.6 install -r requirements.txt
#  func_exist_status
#  echo -e "\e[32m#########Restart services #########\e[0m"
#  func_servicerestart