- name: Setup the shipping service
  hosts: all
  become: true
  vars:
    component: shipping
    schema: true
  tasks:
    - name: Import the Java application set up
      ansible.builtin.import_tasks: java.yml



#component=shipping
#schema_type=mysql
#source comman.sh
#func_java